/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WhaleRouteImport } from './routes/whale'
import { Route as PerformanceRouteImport } from './routes/performance'
import { Route as ExchangeRouteImport } from './routes/exchange'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPublicHooksKpkSignalsCronRouteImport } from './routes/api/public/hooks/kpk-signals-cron'

const WhaleRoute = WhaleRouteImport.update({
  id: '/whale',
  path: '/whale',
  getParentRoute: () => rootRouteImport,
} as any)
const PerformanceRoute = PerformanceRouteImport.update({
  id: '/performance',
  path: '/performance',
  getParentRoute: () => rootRouteImport,
} as any)
const ExchangeRoute = ExchangeRouteImport.update({
  id: '/exchange',
  path: '/exchange',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksKpkSignalsCronRoute =
  ApiPublicHooksKpkSignalsCronRouteImport.update({
    id: '/api/public/hooks/kpk-signals-cron',
    path: '/api/public/hooks/kpk-signals-cron',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/exchange': typeof ExchangeRoute
  '/performance': typeof PerformanceRoute
  '/whale': typeof WhaleRoute
  '/api/public/hooks/kpk-signals-cron': typeof ApiPublicHooksKpkSignalsCronRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/exchange': typeof ExchangeRoute
  '/performance': typeof PerformanceRoute
  '/whale': typeof WhaleRoute
  '/api/public/hooks/kpk-signals-cron': typeof ApiPublicHooksKpkSignalsCronRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/exchange': typeof ExchangeRoute
  '/performance': typeof PerformanceRoute
  '/whale': typeof WhaleRoute
  '/api/public/hooks/kpk-signals-cron': typeof ApiPublicHooksKpkSignalsCronRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/exchange'
    | '/performance'
    | '/whale'
    | '/api/public/hooks/kpk-signals-cron'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/exchange'
    | '/performance'
    | '/whale'
    | '/api/public/hooks/kpk-signals-cron'
  id:
    | '__root__'
    | '/'
    | '/exchange'
    | '/performance'
    | '/whale'
    | '/api/public/hooks/kpk-signals-cron'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ExchangeRoute: typeof ExchangeRoute
  PerformanceRoute: typeof PerformanceRoute
  WhaleRoute: typeof WhaleRoute
  ApiPublicHooksKpkSignalsCronRoute: typeof ApiPublicHooksKpkSignalsCronRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/whale': {
      id: '/whale'
      path: '/whale'
      fullPath: '/whale'
      preLoaderRoute: typeof WhaleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/performance': {
      id: '/performance'
      path: '/performance'
      fullPath: '/performance'
      preLoaderRoute: typeof PerformanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exchange': {
      id: '/exchange'
      path: '/exchange'
      fullPath: '/exchange'
      preLoaderRoute: typeof ExchangeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/kpk-signals-cron': {
      id: '/api/public/hooks/kpk-signals-cron'
      path: '/api/public/hooks/kpk-signals-cron'
      fullPath: '/api/public/hooks/kpk-signals-cron'
      preLoaderRoute: typeof ApiPublicHooksKpkSignalsCronRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ExchangeRoute: ExchangeRoute,
  PerformanceRoute: PerformanceRoute,
  WhaleRoute: WhaleRoute,
  ApiPublicHooksKpkSignalsCronRoute: ApiPublicHooksKpkSignalsCronRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
