/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPublicHooksKpkSignalsCronRouteImport } from './routes/api/public/hooks/kpk-signals-cron'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksKpkSignalsCronRoute =
  ApiPublicHooksKpkSignalsCronRouteImport.update({
    id: '/api/public/hooks/kpk-signals-cron',
    path: '/api/public/hooks/kpk-signals-cron',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/public/hooks/kpk-signals-cron': typeof ApiPublicHooksKpkSignalsCronRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/public/hooks/kpk-signals-cron': typeof ApiPublicHooksKpkSignalsCronRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/public/hooks/kpk-signals-cron': typeof ApiPublicHooksKpkSignalsCronRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/api/public/hooks/kpk-signals-cron'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/api/public/hooks/kpk-signals-cron'
  id: '__root__' | '/' | '/api/public/hooks/kpk-signals-cron'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiPublicHooksKpkSignalsCronRoute: typeof ApiPublicHooksKpkSignalsCronRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/kpk-signals-cron': {
      id: '/api/public/hooks/kpk-signals-cron'
      path: '/api/public/hooks/kpk-signals-cron'
      fullPath: '/api/public/hooks/kpk-signals-cron'
      preLoaderRoute: typeof ApiPublicHooksKpkSignalsCronRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiPublicHooksKpkSignalsCronRoute: ApiPublicHooksKpkSignalsCronRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
